using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PropertyTenants.Infrastructure.MappingConfigurations.Store
{
    //public class BlogConfiguration : IEntityTypeConfiguration<Dictionary<string, object>>
    //{
    //    public void Configure(EntityTypeBuilder<Dictionary<string, object>> builder)
    //    {
    //        // Map to the Blog table
    //        builder.ToTable("Blog");

    //        // Configure BlogId as the primary key with auto-increment
    //        builder.Property<int>("BlogId")
    //            .HasColumnName("BlogId")
    //            .ValueGeneratedOnAdd(); // Auto-incrementing ID

    //        // Configure Url property
    //        builder.Property<string>("Url")
    //            .HasColumnName("Url")
    //            .IsRequired() // Non-nullable
    //            .HasMaxLength(500); // Limit length for performance

    //        // Configure LastUpdated with SQL Server-generated date
    //        builder.Property<DateTime>("LastUpdated")
    //            .HasColumnName("LastUpdated")
    //            .HasDefaultValueSql("GETDATE()") // SQL Server sets the current date/time
    //            .ValueGeneratedOnAdd(); // Value is generated by the database on insert

    //        // Set BlogId as the primary key
    //        builder.HasKey("BlogId");
    //    }
    //}
}
