// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class AddressAttributeValue
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int AddressAttributeId { get; set; }

    public bool IsPreSelected { get; set; }

    public int DisplayOrder { get; set; }

    public virtual AddressAttribute AddressAttribute { get; set; }
}