// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class AddressAttribute
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsRequired { get; set; }

    public int AttributeControlTypeId { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<AddressAttributeValue> AddressAttributeValues { get; set; } = new List<AddressAttributeValue>();
}