// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class Campaign
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public int StoreId { get; set; }

    public int CustomerRoleId { get; set; }

    public int NewsLetterSubscriptionTypeId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public DateTime? DontSendBeforeDateUtc { get; set; }
}