// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class EmailAccount
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string Host { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int Port { get; set; }

    public bool EnableSsl { get; set; }

    public int MaxNumberOfEmails { get; set; }

    public int EmailAuthenticationMethodId { get; set; }

    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public string TenantId { get; set; }

    public virtual ICollection<QueuedEmail> QueuedEmails { get; set; } = new List<QueuedEmail>();
}