// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ForumsPostVote
{
    public int Id { get; set; }

    public int ForumPostId { get; set; }

    public int CustomerId { get; set; }

    public bool IsUp { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public virtual ForumsPost ForumPost { get; set; }
}