// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ForumsPost
{
    public int Id { get; set; }

    public string Text { get; set; }

    public string Ipaddress { get; set; }

    public int CustomerId { get; set; }

    public int TopicId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public DateTime UpdatedOnUtc { get; set; }

    public int VoteCount { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<ForumsPostVote> ForumsPostVotes { get; set; } = new List<ForumsPostVote>();

    public virtual ForumsTopic Topic { get; set; }
}