// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class GenericAttribute
{
    public int Id { get; set; }

    public string KeyGroup { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public int EntityId { get; set; }

    public int StoreId { get; set; }

    public DateTime? CreatedOrUpdatedDateUtc { get; set; }
}