// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class LocaleStringResource
{
    public int Id { get; set; }

    public string ResourceName { get; set; }

    public string ResourceValue { get; set; }

    public int LanguageId { get; set; }

    public virtual Language Language { get; set; }
}