// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class NewsLetterSubscription
{
    public int Id { get; set; }

    public int TypeId { get; set; }

    public string Email { get; set; }

    public Guid NewsLetterSubscriptionGuid { get; set; }

    public bool Active { get; set; }

    public int StoreId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public int LanguageId { get; set; }

    public virtual NewsLetterSubscriptionType Type { get; set; }
}