// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class NewsLetterSubscriptionType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool TickedByDefault { get; set; }

    public int DisplayOrder { get; set; }

    public bool LimitedToStores { get; set; }

    public virtual ICollection<NewsLetterSubscription> NewsLetterSubscriptions { get; set; } = new List<NewsLetterSubscription>();
}