// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class PermissionRecord
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SystemName { get; set; }

    public string Category { get; set; }

    public virtual ICollection<CustomerRole> CustomerRoles { get; set; } = new List<CustomerRole>();
}