// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class PictureBinary
{
    public int Id { get; set; }

    public int PictureId { get; set; }

    public byte[] BinaryData { get; set; }

    public virtual Picture Picture { get; set; }
}