// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class PollAnswer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int PollId { get; set; }

    public int NumberOfVotes { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Poll Poll { get; set; }

    public virtual ICollection<PollVotingRecord> PollVotingRecords { get; set; } = new List<PollVotingRecord>();
}