// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ViewPath { get; set; }

    public int DisplayOrder { get; set; }

    public string IgnoredProductTypes { get; set; }
}