// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductWarehouseInventory
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int WarehouseId { get; set; }

    public int StockQuantity { get; set; }

    public int ReservedQuantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}