// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductAttributeValuePicture
{
    public int Id { get; set; }

    public int ProductAttributeValueId { get; set; }

    public int PictureId { get; set; }

    public virtual ProductAttributeValue ProductAttributeValue { get; set; }
}