// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductTag
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string MetaKeywords { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDescription { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}