// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductReviewReviewTypeMapping
{
    public int Id { get; set; }

    public int ProductReviewId { get; set; }

    public int ReviewTypeId { get; set; }

    public int Rating { get; set; }

    public virtual ProductReview ProductReview { get; set; }

    public virtual ReviewType ReviewType { get; set; }
}