// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class ProductAttributeCombinationPicture
{
    public int Id { get; set; }

    public int ProductAttributeCombinationId { get; set; }

    public int PictureId { get; set; }

    public virtual ProductAttributeCombination ProductAttributeCombination { get; set; }
}