// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class RecurringPaymentHistory
{
    public int Id { get; set; }

    public int RecurringPaymentId { get; set; }

    public int OrderId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public virtual RecurringPayment RecurringPayment { get; set; }
}