// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class SearchTerm
{
    public int Id { get; set; }

    public string Keyword { get; set; }

    public int StoreId { get; set; }

    public int Count { get; set; }
}