// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class SpecificationAttributeOption
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ColorSquaresRgb { get; set; }

    public int SpecificationAttributeId { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<ProductSpecificationAttributeMapping> ProductSpecificationAttributeMappings { get; set; } = new List<ProductSpecificationAttributeMapping>();

    public virtual SpecificationAttribute SpecificationAttribute { get; set; }
}