// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class StoreMapping
{
    public int Id { get; set; }

    public string EntityName { get; set; }

    public int StoreId { get; set; }

    public int EntityId { get; set; }

    public virtual Store Store { get; set; }
}