// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class UrlRecord
{
    public int Id { get; set; }

    public string EntityName { get; set; }

    public string Slug { get; set; }

    public int EntityId { get; set; }

    public bool IsActive { get; set; }

    public int LanguageId { get; set; }
}