// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class VendorNote
{
    public int Id { get; set; }

    public string Note { get; set; }

    public int VendorId { get; set; }

    public DateTime CreatedOnUtc { get; set; }

    public virtual Vendor Vendor { get; set; }
}