// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class Video
{
    public int Id { get; set; }

    public string VideoUrl { get; set; }

    public virtual ICollection<ProductVideo> ProductVideos { get; set; } = new List<ProductVideo>();
}