// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nopreverseengineering.Models;

public partial class Warehouse
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string AdminComment { get; set; }

    public int AddressId { get; set; }

    public virtual ICollection<ProductWarehouseInventory> ProductWarehouseInventories { get; set; } = new List<ProductWarehouseInventory>();
}